#!/bin/bash
[[ -z "$1" ]] && exit 0
[[ -z "$2" ]] && exit 0
for(( index = 0; index<$1 ; index++ )) ; do
	CHARS+=$( printf "\U$( printf "%X" $[ 0x$2 + $index ] )" )
done
uniname -bcep <<< "$CHARS" | sed "1 d;$ d"