#!/bin/bash

UNICODE="/usr/share/unicode/Blocks.txt"
[[ -r $UNICODE ]] || exit 1

LISTNUM=28
DMENUOPT="-i -l 30 -p UNICODE: -w $( xdotool getwindowfocus ) "

CATEGORY=$( sed "/^ *$/d;/#/d" "$UNICODE" | dmenu $DMENUOPT)
[[ -z "$CATEGORY" ]] && exit 1

START=${CATEGORY%%\.*}

CHARS="UNICODE:"

function listUni {
	OPT=$( echo -e "NEXT\nPREV\n$(print-unicode-seq $LISTNUM $START )" | dmenu $DMENUOPT -p "$CHARS" )
	if [[ $OPT == PREV ]]; then
		START=$( printf "%X" $[ 0x$START - $LISTNUM ]  )
	elif [[ $OPT == NEXT ]]; then
		START=$( printf "%X" $[ 0x$START + $LISTNUM ]  )
	elif [[ -z $OPT ]] ; then
		[[ $CHARS == "UNICODE:" ]] && CHARS=""
		xdotool type "$CHARS"
		exit 0
	else
		[[ $CHARS == "UNICODE:" ]] && CHARS=""
		CHARS+="$( cut -d' ' -f 3 <<< "$OPT" )"
	fi
}

while true; do
	listUni
done
