#!/bin/bash
UNICODEFILE="/usr/share/unicode/UnicodeData.txt"
[[ -r "$UNICODEFILE" ]] || { echo "This script requieres the UnicodeData.txt file from the package unicode-character-database"; exit 1; }
CHAR=$( dmenu -i -w $( xdotool getwindowfocus ) -l 5 -p "unicode" < $UNICODEFILE | cut -d";" -f 1);
[[ -z $CHAR ]] && exit 0
for unicode in $CHAR
do
	UNICODE+=$( printf "\U$unicode" )
done
xdotool type "$UNICODE"
printf "$UNICODE" | xclip -i -select clipboard
