#!/bin/bash
# Here's a useful code you can have for free, text me if you like it ;)
UNICODEFILE="/usr/share/unicode/UnicodeData.txt"
CACHE="$HOME/.cache/unicode"
LIMIT=5
[[ -r "$UNICODEFILE" ]] || { echo "This script requieres the UnicodeData.txt file from the package unicode-character-database"; exit 1; }
[[ -r "$CACHE" ]] || echo > $CACHE
CHAR=$( cat $CACHE $UNICODEFILE |  dmenu -i -w $( xdotool getwindowfocus ) -l 8 -p "unicode" );
[[ -z $CHAR ]] && exit 0
echo $CHAR | cat -  $CACHE > "${CACHE}_tmp" && mv "${CACHE}_tmp" $CACHE
CHAR=$( cut -d ";" -f 1 <<< "$CHAR" )
for unicode in $CHAR
do
	UNICODE+=$( printf "\U$unicode" )
done
xdotool type "$UNICODE"
printf "$UNICODE" | xclip -i -select clipboard
[[ "$( wc -l < $CACHE )" -gt "$LIMIT" ]] && head -n $LIMIT $CACHE > "${CACHE}_tmp"  && mv "${CACHE}_tmp" $CACHE
